rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
    - "rmcs_core::hardware::Dart -> dart"
    - "rmcs_core::broadcaster::ValueBroadcaster -> Value_Broadcaster"

dart:
  ros__parameters:
    usb_pid_top_board: -1
    external_imu_port: external_imu_port
    imu_sensitivity: 2.0
    first_sample_spot: 1.0
    final_sample_spot: 5.0

Value_Broadcaster:
  ros__parameters:
    forward_list:
      - "/tf"
      - "/gimbal/state/roll"
      - "/gimbal/state/pitch"
      - "/gimbal/state/yaw"
      - "/gimbal/state/final_roll"
      - "/gimbal/state/final_pitch"
      - "/gimbal/state/filtered_yaw"
      - "/gimbal/state/final_yaw"