rmcs_executor:
  ros__parameters:
     update_rate: 1000.0
     components:
      - "rmcs_core::hardware::Gantry -> gantry_hardware"
      - "rmcs_core::controller::GantryController -> gantry_controller"
      - "rmcs_core::controller::GantryInformation -> gantry_information"
      - "rmcs_core::broadcaster::ValueBroadcaster -> Value_Broadcaster"

gantry_hardware:
  ros__parameters:
      usb_pid_bottom_board: -1

gantry_controller:
  ros__parameters: {}


gantry_information:
  ros__parameters:
    left_motor_angle_to_velocity_kp: 10.0
    left_motor_angle_to_velocity_ki: 0.0
    left_motor_angle_to_velocity_kd: 0.0
    left_motor_angle_to_velocity_integral_min: -1000.0
    left_motor_angle_to_velocity_integral_max: 1000.0
    left_motor_angle_to_velocity_integral_split_min: -1000.0
    left_motor_angle_to_velocity_integral_split_max: 1000.0
    left_motor_angle_to_velocity_output_min: -1000.0
    left_motor_angle_to_velocity_output_max: 1000.0

    right_motor_angle_to_velocity_kp: 10.0
    right_motor_angle_to_velocity_ki: 0.0
    right_motor_angle_to_velocity_kd: 0.0
    right_motor_angle_to_velocity_integral_min: -1000.0
    right_motor_angle_to_velocity_integral_max: 1000.0
    right_motor_angle_to_velocity_integral_split_min: -1000.0
    right_motor_angle_to_velocity_integral_split_max: 1000.0
    right_motor_angle_to_velocity_output_min: -1000.0
    right_motor_angle_to_velocity_output_max: 1000.0

    left_motor_velocity_to_torques_kp: 10.0
    left_motor_velocity_to_torques_ki: 0.0
    left_motor_velocity_to_torques_kd: 0.0
    left_motor_velocity_to_torques_integral_min: -1000.0
    left_motor_velocity_to_torques_integral_max: 1000.0
    left_motor_velocity_to_torques_integral_split_min: -1000.0
    left_motor_velocity_to_torques_integral_split_max: 1000.0
    left_motor_velocity_to_torques_output_min: -1000.0
    left_motor_velocity_to_torques_output_max: 1000.0

    right_motor_velocity_to_torques_kp: 10.0
    right_motor_velocity_to_torques_ki: 0.0
    right_motor_velocity_to_torques_kd: 0.0
    right_motor_velocity_to_torques_integral_min: -1000.0
    right_motor_velocity_to_torques_integral_max: 1000.0
    right_motor_velocity_to_torques_integral_split_min: -1000.0
    right_motor_velocity_to_torques_integral_split_max: 1000.0
    right_motor_velocity_to_torques_output_min: -1000.0
    right_motor_velocity_to_torques_output_max: 1000.0


Value_Broadcaster:
  ros__parameters:
    forward_list:
      - /gantry/left_motor/angle
      - /gantry/right_motor/angle
      - /gantry/left_motor/velocity
      - /gantry/right_motor/velocity
      - /gantry/left_motor/filtered_velocity
      - /gantry/right_motor/filtered_velocity
      - /gantry/left_motor/torque
      - /gantry/right_motor/torque
      - /gantry/left_motor/control_torque
      - /gantry/control_angle