rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::controller::SinCosGenerator -> sin_cos_generator
      - rmcs_core::controller::ComponentB -> component_b
      - rmcs_core::broadcaster::ValueBroadcaster -> value_broadcaster




sin_cos_generator:
  ros__parameters:
    omega: 10.0

desired_velocity_publisher:
  ros__parameters:
    desired_velocity: 50.0

value_broadcaster:
  ros__parameters:
    forward_list:
      - /sin
      - /cos
      - /sum